/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem.gui;

import hospitalmanagmentsystem.dao.AppointmentDao;
import hospitalmanagmentsystem.dao.DoctorsDao;
import hospitalmanagmentsystem.dao.PatientDao;
import hospitalmanagmentsystem.pojo.AppointmentPojo;
import hospitalmanagmentsystem.pojo.PatientPojo;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Aftab
 */
public class UpdatePatientFrame extends javax.swing.JFrame {
   
   private PatientPojo patient;
    private java.util.Date d;
   
   private ArrayList<String> patientIds;
    private ArrayList<String> doctorIds;

    /**
     * Creates new form UpdatePatientFrame
     */
    public UpdatePatientFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadProductDetails();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtOpd = new javax.swing.JTextField();
        jcDocId = new javax.swing.JComboBox<>();
        jcPatientId = new javax.swing.JComboBox<>();
        txtAge = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtFName = new javax.swing.JTextField();
        txtSName = new javax.swing.JTextField();
        jcGender = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        txtMno = new javax.swing.JTextField();
        jcStatus = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Patient Frame");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Luminari", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Sanjeevani  Application ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 523, 12));

        jSeparator1.setBackground(new java.awt.Color(250, 248, 196));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 550, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(234, 243, 250));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("OPD");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 46, 74, 28));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("First Name");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, 23));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Age");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 74, 20));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Marial Status");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 23));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("City");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 74, 20));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("DoctorId");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 95, -1, 21));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Patient Id");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 137, 74, 25));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Gender");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 75, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Last Name");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 94, 21));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Phone No.");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 19));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Date");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 72, 24));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Address");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 264, 74, 26));

        txtOpd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtOpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 220, -1));

        jcDocId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(jcDocId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 220, -1));

        jcPatientId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPatientIdActionPerformed(evt);
            }
        });
        jPanel5.add(jcPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 220, -1));

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 220, -1));

        txtCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 220, -1));

        txtAddress.setColumns(10);
        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 226, 44));

        txtFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 150, 20));

        txtSName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 150, -1));

        jcGender.setEditable(true);
        jcGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        jPanel5.add(jcGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 150, -1));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 155, 24));

        txtMno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(txtMno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 155, -1));

        jcStatus.setEditable(true);
        jcStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARRIED", "UNMARRIED" }));
        jPanel5.add(jcStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 150, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 698, 325));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagmentsystem/icon/images (2).jpg"))); // NOI18N
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, 243));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Update Patient Frame");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 35));

        btnBack3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(0, 153, 153));
        btnBack3.setText("HOME");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 111, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 105, -1));

        btnLogout1.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(0, 153, 153));
        btnLogout1.setText("Logout");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 107, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 218, 27));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1010, 370));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagmentsystem/icon/HomePageBG1.jpg"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -230, 1010, 570));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ReceptionistOptionsFrame pof=new ReceptionistOptionsFrame();
        pof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(validateInput()==false)
       {
           return;
       }
         try{
            
            patient.setAptStatus("REQUEST");
            System.out.println(patient);
            
             AppointmentPojo appointment = new AppointmentPojo();
            appointment.setPatientId(patient.getPatientId());
            appointment.setPatientName(patient.getFirstName()+patient.getLastName());
            appointment.setStatus(patient.getAptStatus());
            appointment.setOpd(patient.getOpd());
            appointment.setAppointmentDate(patient.getDate().toString());
            appointment.setDoctorName(DoctorsDao.getDoctorNameById(patient.getDoctorId()));
            if(PatientDao.updatePatient(patient) && AppointmentDao.updateAppointment(appointment)){
                JOptionPane.showMessageDialog(null,"update patient booking Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
                clearAll();
            }
            else
                    JOptionPane.showMessageDialog(null,"Unable to Update patient booking!","Error",JOptionPane.ERROR_MESSAGE);
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error in update patient!","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        LoginFrame lf=new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void jcPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPatientIdActionPerformed
        // TODO add your handling code here:
        try{
            String patientId=jcPatientId.getSelectedItem().toString();
            PatientPojo patient=PatientDao.getPatientDetailsById(patientId);
            if (patient == null){
                JOptionPane.showMessageDialog(null,"No data found.","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            System.out.println("patient detail :"+patient);
            //setting the data 
            txtOpd.setText(patient.getOpd());
            txtFName.setText(patient.getFirstName());
            txtSName.setText(patient.getLastName());
            txtAge.setText(String.valueOf(patient.getAge()));
            txtAddress.setText(patient.getAddress());
            txtCity.setText(patient.getCity());
            txtMno.setText(patient.getMno());
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/YYYY");
            String sDate=sdf.format(patient.getDate());
            txtDate.setText(sDate);
            
            
            jcGender.setSelectedItem(patient.getGender());
            jcStatus.setSelectedItem(patient.getMarriedStatus());
            jcDocId.setSelectedItem(patient.getDoctorId());
              
             
        }
        catch(Exception npx){
            System.out.println(" no doctors available to be added ");
            //JOptionPane.showMessageDialog(null,"no receptionist available to be added!","Information",JOptionPane.INFORMATION_MESSAGE);
            npx.printStackTrace();
        }
    }//GEN-LAST:event_jcPatientIdActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        AdminOptionsFrame aof=new AdminOptionsFrame();
        aof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcDocId;
    private javax.swing.JComboBox<String> jcGender;
    private javax.swing.JComboBox<String> jcPatientId;
    private javax.swing.JComboBox<String> jcStatus;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtMno;
    private javax.swing.JTextField txtOpd;
    private javax.swing.JTextField txtSName;
    // End of variables declaration//GEN-END:variables

    public void loadProductDetails(){
        try{
            patientIds=PatientDao.getAllPatientId();
            for(String str:patientIds)
            {
                jcPatientId.addItem(str);
            }
            doctorIds=PatientDao.getAllPatientDoctorId();
            for(String str:doctorIds)
            {
                jcDocId.addItem(str);
            }
        
//              txtOpd.setText(patient.getOpd());
//              jcPatientId.addItem(patient.getP_id());
//              
//              jcWardNo.addItem(patient.getW_no());
//              //jcBedNo.removeAllItems();
//              jcBedNo.addItem(String.valueOf(patient.getB_no()));
//              txtFName.setText(patient.getF_name());
//              txtSName.setText(patient.getS_name());
//              txtAge.setText(String.valueOf(patient.getAge()));
//              jcGender.removeAllItems();
//              jcGender.addItem(patient.getGender());
//              jcMStatus.removeAllItems();
//              jcMStatus.addItem(patient.getM_status());
//              txtDate.setText(String.valueOf(patient.getDate()));
//              txtAddress.setText(patient.getAddress());
//              txtCity.setText(patient.getCity());
//              txtMno.setText(patient.getMno());
              
              
          
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error while fetching IDS!","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
}
public void clearAll(){
              txtOpd.setText("");
              txtFName.setText("");
              txtSName.setText("");
              txtAge.setText("");
              txtDate.setText("");
              txtAddress.setText("");
              txtCity.setText("");
              txtMno.setText("");
              jcGender.setSelectedIndex(0);
                jcStatus.setSelectedIndex(0);
                jcDocId.setSelectedIndex(0);
     }

     public boolean validateInput()
    {
        patient = new PatientPojo();
        patient.setFirstName(txtFName.getText());
        patient.setDoctorId(jcDocId.getSelectedItem().toString());
        patient.setLastName(txtSName.getText());
        patient.setPatientId(jcPatientId.getSelectedItem().toString());
        patient.setOpd(txtOpd.getText());
        patient.setGender(jcGender.getSelectedItem().toString());
        patient.setMarriedStatus(jcStatus.getSelectedItem().toString());
        patient.setAddress(txtAddress.getText());
        patient.setCity(txtCity.getText());
        patient.setMno(txtMno.getText());
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MMM/YYYY");
        java.util.Date mydate;
       try {
           mydate = sdf.parse(txtDate.getText());
           java.sql.Date date=new java.sql.Date(mydate.getTime());
            patient.setDate(date);
       } catch (ParseException ex) {
           ex.printStackTrace();
       }
        
        
        
        
        if(patient.getFirstName().isEmpty()||patient.getLastName().isEmpty()||txtAge.getText().isEmpty()||patient.getOpd().isEmpty()||patient.getAddress().isEmpty()||patient.getCity().isEmpty()||patient.getMno().isEmpty())
        {
            JOptionPane.showMessageDialog(null,  "please fill all field first!!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try{
        patient.setAge(Integer.parseInt(txtAge.getText()));
        }catch(NumberFormatException nfx){
            JOptionPane.showMessageDialog(null, "Please Input Numberic Age! Try Again.", "Error!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
       if(patient.getAge()<=0)
       {
           JOptionPane.showMessageDialog(null, "error", "please input valid age!!", JOptionPane.ERROR_MESSAGE);
           return false;
       }
       
        System.out.println("mobile validation : "+!isValidMobileNo(patient.getMno()));
       if(!isValidMobileNo(patient.getMno()))
       {
           JOptionPane.showMessageDialog(null, "please input valid mobile number!","error", JOptionPane.ERROR_MESSAGE);
           return false;
       }
       
        return true;
        
       
    }
    
//    public boolean mnoValidate()
//    {
//        Pattern p=Pattern.compile("(0/91)?[6-9][0-9]{9}");
//        Matcher m=p.matcher(mno);
//        return (m.find()&&m.group().equals(m));
//    }
    
    public static boolean isValidMobileNo(String str)  
    {  
        //(0/91): number starts with (0/91)  
        //[7-9]: starting of the number may contain a digit between 0 to 9  
        //[0-9]: then contains digits 0 to 9  
        Pattern ptrn = Pattern.compile("(0/91)?[6-9][0-9]{9}");  
        //the matcher() method creates a matcher that will match the given input against this pattern  
        Matcher match = ptrn.matcher(str);  
        //returns a boolean value  
        return (match.find() && match.group().equals(str));  
    }

}
